### ISSUE TITLE
Update path_provider

### ISSUE THREAD

**Issue by xantiagoma** [phillwiggins/flutter_parse_sdk#212]
I'm getting following error when tried to use flutter_map with this library.
```
[appx] flutter packages get
Running "flutter packages get" in appx...                    
Because every version of flutter_map from git depends on path_provider ^1.1.0 and every version of parse_server_sdk from git depends on path_provider ^0.5.0+1, flutter_map from git is incompatible with parse_server_sdk from git.

So, because appx depends on both parse_server_sdk from git and flutter_map from git, version solving failed.
pub get failed (1)
exit code 1
```

**Comment by phillwiggins** [comment]
Hey Santiago

I'll ensure all libraries are updated for the next release.

Thanks for pointing that out.

**Comment by phillwiggins** [comment]
It's been added to version 1.0.23 (Not released as of yet). You can use it still in your pubspec.yaml:-

```
parse_server_sdk:
    git:
      url: git://github.com/phillwiggins/flutter_parse_sdk.git
      ref: release/1.0.23
```
